# Generated by Django 3.1.3 on 2020-12-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201205_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='money',
            field=models.FloatField(default=100),
        ),
    ]
