# Generated by Django 3.1.3 on 2020-12-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201210_0954'),
        ('API', '0003_auto_20201210_1009'),
    ]

    operations = [
    ]
