# Generated by Django 3.1.3 on 2020-12-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_merge_20201210_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingdetails',
            name='users',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='shopping_detail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShoppingDetails',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
