# Generated by Django 3.1.3 on 2020-12-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_auto_20201210_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meansofpayment',
            name='description',
            field=models.CharField(default='Card', max_length=100, unique=True),
        ),
    ]
