image: python:3.6.1

services:
    - postgres:9.3

variables:
  POSTGRES_DB: project_ci_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

test:
    script:
    - export DATABASE_URL=postgres://postgres:@localhost:5432/project_ci_test
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python api/manage.py makemigrations
    - python api/manage.py migrate
    - python api/manage.py test api