image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/bigshoes/django/djangopg .
    - docker push registry.gitlab.com/bigshoes/django/djangopg
  only : 
    - main
    - gaetan_dev
# pour squizer le build parceque c'est chiant et long

test:
  stage: test
  script:
    - docker pull registry.gitlab.com/bigshoes/django/djangopg:latest
    - docker run --name API -p 8000:8000 -d registry.gitlab.com/bigshoes/django/djangopg:latest
    - docker exec -it API "python3 BackEnd/manage.py test"

deploy:
  stage: deploy
  script:
    - docker pull registry.gitlab.com/bigshoes/django/djangopg:latest
    - docker run --name API -p 8000:8000 -d registry.gitlab.com/bigshoes/django/djangopg:latest
    - docker exec -it API "python3 BackEnd/manage.py runserver 0.0.0.0:8000 --noreload"
