image: python:3.6.1

services:
    - postgres:9.3

variables:
  POSTGRES_DB: project_ci_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
before_script:
  - export DATABASE_URL=postgres://postgres:@postgres:5432/project_ci_test
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - python api/manage.py makemigrations
  - python api/manage.py migrate
test:
    script:
    - python api/manage.py test tdev800
deploy:
  stage: deploy
  script:
    - echo "Deploy to production server"
    - python api/manage.py runserver
  environment:
    name: production
    url: https://tdev800.com
    kubernetes:
      namespace: production