image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/bigshoes/django/djangopg api/.
    - docker push registry.gitlab.com/bigshoes/django/djangopg
  only : 
    - master 
# pour squizer le build parceque c'est chiant et long

deploy:
  stage: deploy
  before_script:
  - apt-get update -qq && apt-get install -y -qq sshpass
  - apk add --no-cache openssh-client bash
  - mkdir -p ~/.ssh
  - echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
  script:
    - bash api/devops/deploy.sh
