image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/bigshoes/django/djangopg api/.
    - docker push registry.gitlab.com/bigshoes/django/djangopg
  only : 
    - master 
# pour squizer le build parceque c'est chiant et long

deploy:
  stage: deploy
  script:
    - docker pull registry.gitlab.com/bigshoes/django/djangopg:latest
    - docker run --name tdev800 -p 8000:8000 -d registry.gitlab.com/bigshoes/django/djangopg:latest
